django_playground/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('playground.urls')),
]

playground/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index),
]

playground/views.py
# from io import StringIO
# from traceback import print_tb

import sqlparse
from django import forms
from django.shortcuts import render

from .run_query import run_query


class PlaygroundForm(forms.Form):
    model_def = forms.CharField(widget=forms.Textarea)
    query = forms.CharField()


def index(request):
    if 'model_def' in request.GET:
        form = PlaygroundForm(request.GET)
        if form.is_valid():
            try:
                qs = run_query(form.cleaned_data.get('model_def'), form.cleaned_data.get('query'))
                context = {
                    'form': form,
                    'sql': sqlparse.format(str(qs.query), reindent=True),
                }
            except Exception as e:
                # output = StringIO()
                # print_tb(e.__traceback__, file=output)
                context = {
                    'form': form,
                    # 'error': output.getvalue(),
                    'error': str(e),
                }
    else:
        context = {
            'form': PlaygroundForm(),
        }

    return render(request, template_name='playground/playground.html', context=context)

playground/templates/playground/base.html
<!doctype html>
<html lang="en">
<head>
 <meta charset="utf-8">
 <meta http-equiv="x-ua-compatible" content="ie=edge">
 <meta name="description" content="">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Django ORM Playground</title>
</head>
<body>
 <h1>Django ORM Playground</h1>
 <h3>Examine the resulting SQL produced by ORM queries</h3>

 <div id="content">
  {% block content %}{% endblock %}
 </div>

</body>
</html>

playground/templates/playground/playground.html
{% extends "playground/base.html" %}

{% block content %}
<div style="display: flex; justify-content: space-between;">
<div>
<style>
#id_query {
 width: 300px;
}
</style>
<form method="get">
 {{ form.as_table }}
 <button>Submit</button>
</form>
{% if sql %}
<p>Resulting SQL:</p>
<pre>
{{ sql }}
</pre>
{% elif error %}
<p>There was an error evaluating your request:</p>
<pre>
{{ error }}
</pre>
{% endif %}
</div>
<div>
<p>Try the following as an example:</p>
<p>Models:
<pre id="model-example">
from django.db import models

class Foo(models.Model):
    from django.db import models
    bar = models.CharField(max_length=255)
</pre>
<button onclick="document.getElementById('id_model_def').value = document.getElementById('model-example').innerText">Use</button>
</p>
<p>Query:
<pre id="query-example">
Foo.objects.filter(bar="bar").order_by("bar")
</pre>
<button onclick="document.getElementById('id_query').value = document.getElementById('query-example').innerText">Use</button>
</p>
</div>
</div>
{% endblock %}